add methods skeleton / create DTO
monitrack/server pull request #4
Opened 2023-07-20 12:47 UTC by SaidkhojaIftikhor

2023-07-20 12:49 UTC, SaidkhojaIftikhor commented on src/Controllers/IncomeController.cs
> +
```suggestion
```

2023-07-20 12:51 UTC, veyxov commented on src/Controllers/IncomeController.cs
> +        // maybe I will surround it by try catch
try catch - bad ❌
errors as values - good ❇️

2023-07-20 12:51 UTC, veyxov commented on src/Models/Income.cs
> +    public required string Category { get; set; }
Category should be a separate table

2023-07-27 12:30 UTC, veyxov requested changes
Great job, take a look at the comments. Feel free to ask questions.

2023-07-27 12:30 UTC, veyxov commented on src/Context/MoniTrackContext.cs
> +    public MoniTrackContext()
There's no need for all of this.

2023-07-27 12:30 UTC, veyxov commented on src/Context/MoniTrackContext.cs
> +        => options.UseSqlite($"Data Source={DbPath}");
`Data Source = app.db` will do the trick for now.

2023-07-27 12:30 UTC, veyxov commented on src/Controllers/IncomeController.cs
> +        _context = new MoniTrackContext();
Please use [DI](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-7.0)

2023-07-27 12:30 UTC, veyxov commented on src/Controllers/IncomeController.cs
> +    public async Task<ActionResult<Income>> GetIncomeInfoById(int id)
Returning a database model, with many relations is problematic.
Circular dependency issues can occur.

2023-07-27 12:30 UTC, veyxov commented on src/Controllers/IncomeController.cs
> +        Income income = new Income()
We can use something like [mapster](https://github.com/MapsterMapper/Mapster)

2023-07-27 12:30 UTC, veyxov commented on src/Dtos/IncomeDto.cs
> +    public string Category { get; set; } = null!;
This should be a table (not string, a concrete type)

2023-07-27 12:32 UTC, veyxov commented on src/Controllers/IncomeController.cs
Maybe rebase, in the future?

2023-07-27 12:32 UTC, veyxov commented on src/Controllers/IncomeController.cs
merge commits clutter the history

2023-07-30 15:48 UTC, SaidkhojaIftikhor commented on src/Models/Income.cs
> +    public required string Category { get; set; }
done

2023-07-30 16:53 UTC, SaidkhojaIftikhor commented on src/Context/MoniTrackContext.cs
> +        => options.UseSqlite($"Data Source={DbPath}");
done

2023-07-30 16:53 UTC, SaidkhojaIftikhor commented on src/Controllers/IncomeController.cs
> +        _context = new MoniTrackContext();
done

2023-07-30 16:53 UTC, SaidkhojaIftikhor commented on src/Context/MoniTrackContext.cs
> +    public MoniTrackContext()
removed

2023-07-30 16:54 UTC, SaidkhojaIftikhor commented on src/Dtos/IncomeDto.cs
> +    public string Category { get; set; } = null!;
done

2023-11-30 06:13 UTC, merged