feat: enhance project generally
monitrack/server pull request #7
Opened 2024-01-12 06:56 UTC by Tojiddin20

- Mostly refactored code, but also added logic for categories and users
- There are 2 types of categories, global and user
- Added AuthController, but we need to refactor and enhance it
- Added EmailService for sending registration emails
- Removed try catches, because they were ugly, we need to find a better solution for handling global errors

2024-01-12 09:49 UTC, veyxov requested changes

2024-01-12 09:49 UTC, veyxov commented on src/Context/ApplicationDbContext.cs
> +    public DbSet<User> Users { get; set; } = null!;
please use `public DbSet... set; } = Set<User>();`

2024-01-12 09:49 UTC, veyxov commented on src/Context/ApplicationDbContext.cs
> +    public DbSet<User> Users { get; set; } = null!;
instead of `= null!;`

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/AuthController.cs
> +        UserValidator validator = new UserValidator();
Why are you validating the dto by hand? Create a middleware. I think fluent validation has a package for this: `FluentValidation.AspNetCore` something like that

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/AuthController.cs
> +        SendEmailConfirmation(user);
This should be async

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/AuthController.cs
> +        if (user == null)
```suggestion
        if (user is null)
```

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/AuthController.cs
> +        if (BCrypt.Net.BCrypt.EnhancedVerify(userDto.Password, user.PasswordHash))
Why `Enhanced`? Isn't it slower? Do we need this level of security?

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/ExpenseController.cs
> +    public async Task<ActionResult<Expense>> Update(int id, UpdateExpenseDto updateExpenseDto)
Returning the main model is not good

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/ExpenseController.cs
> +        expense.Amount = updateExpenseDto.Amount;
Use constructor or 
```
var something = new SomeType {
  a = dto.a,
  b = dto.b, 
};
```
or 
```
var model = dto.MapTo<Model>();
```

2024-01-12 09:49 UTC, veyxov commented on src/Controllers/ExpenseController.cs
> +        expense.Amount = updateExpenseDto.Amount;
This is update, Ok

2024-01-12 09:49 UTC, veyxov commented on src/Program.cs
> +builder.Services.AddTransient<IEmailService, EmailService>();
Why transient?
t

2024-01-12 09:49 UTC, veyxov commented on src/Validators/CategoryValidator.cs
> +            .Must(BeAUniqueName)
Inserting business logic into the validator?

2024-01-12 09:49 UTC, veyxov commented on src/sqlite.db
Please remove database files for the PR

2024-01-12 09:51 UTC, veyxov commented
>     * Removed try catches, because they were ugly, we need to find a better solution for handling global errors
You can use the `Result<T>` pattern for error handling.

2024-01-15 11:33 UTC, Tojiddin20 commented on src/Program.cs
> +builder.Services.AddTransient<IEmailService, EmailService>();
корочи 3 та бдай, транзиет, скопе и синглетоне. Хами созай барои и кора (памята холи мена)

2024-01-15 11:35 UTC, Tojiddin20 commented on src/Validators/CategoryValidator.cs
> +            .Must(BeAUniqueName)
Корочи, Исмоил мега соз нестай истифода бурдани БД да валидатор. Чзе ки ба бизнес дахл дора вай бизнес лоҷикай

2024-01-15 12:01 UTC, Tojiddin20 commented on src/Validators/CategoryValidator.cs
> +            .Must(BeAUniqueName)
Соответственно внутри валидации ты должен просто проверить данные на валидность, а то что связанно с логикой - отдельно

2024-01-22 04:18 UTC, veyxov approved these changes

2024-01-22 04:18 UTC, merged